version: 2

jobs:
    test:
        docker:
            - image: circleci/python:3.7
        steps:
            - checkout
            - run: pip install tox --user
            - run: echo 'export PATH=$PATH:/home/circleci/.local/bin' >> $BASH_ENV
            - run: echo `tox --version`
            - run: tox


workflows:
    version: 2
    push:
        jobs:
            - test
