version: 2

jobs:
    test:
        docker:
            - image: circleci/python:3.7
        steps:
            - checkout
            - run: pip install tox --user
            - run: echo 'export PATH=$PATH:/home/circleci/.local/bin' >> $BASH_ENV
            - run: echo `tox --version`
            - run: tox

    release:
        docker:
            - image: circleci/python:3.7
        steps:
            - checkout
            - run: pip install bump2version --user
            - run: echo 'export PATH=$PATH:/home/circleci/.local/bin' >> $BASH_ENV
            # Tag the current release
            - run: bump2version --verbose --no-commit none
            - run: git push origin master --tags
            - run: make release
            # Bump patch for next version
            - run: git checkout develop
            - run: bump2version --verbose --no-tag patch
            - run: git push origin develop


workflows:
    version: 2
    push:
        jobs:
            - test
            - release:
                requires:
                    - test
                filters:
                    branches:
                        only: master
