version: 2

jobs:
    test:
        docker:
            - image: circleci/python3.7
        steps:
            - checkout
            - run: pip install tox
            - run: tox


workflows:
    version: 2
    push:
        jobs:
            - test
